name: OSSF Scorecard

on:
  schedule:
    - cron: "0 3 * * 0" # semanal
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
          if-no-files-found: ignore

